[build]
target = "thumbv7em-none-eabihf"

[env]
RKTK_CONFIG_PATH = { value = "rktk.json", relative = true }
DEFMT_LOG = "debug"

[profile.release]
debug = true
opt-level = "z"
lto = "fat"
panic = "abort"
codegen-units = 1
rustflags = ["-Zlocation-detail=none"]

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["panic_immediate_abort", "optimize_for_size"]

[alias]
run-usb = "run --config .cargo/config_deploy_usb.toml --features defmt-usb"
run-probe = "run --config .cargo/config_deploy_probe.toml --features defmt-rtt"
